<a href="https://colab.research.google.com/github/Tamannapanwar17/Artificial-Neural-Network/blob/main/HyperParameter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('diabetes.csv')

In [ ]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [ ]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [ ]:
x = sc.fit_transform(x)

In [ ]:
x.shape

(768, 8)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [ ]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense,Dropout

In [ ]:
model = Sequential()

In [ ]:
model.add(Dense(32,activation='relu',input_dim=8))
model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.fit(x_train,y_train,batch_size=32,epochs=100,validation_data=(x_test,y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4564 - val_accuracy: 0.7727 - val_loss: 0.4583
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7866 - loss: 0.4547 - val_accuracy: 0.7792 - val_loss: 0.4579
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7883 - loss: 0.4537 - val_accuracy: 0.7792 - val_loss: 0.4577
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7850 - loss: 0.4520 - val_accuracy: 0.7792 - val_loss: 0.4581
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7883 - loss: 0.4507 - val_accuracy: 0.7792 - val_loss: 0.4573
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7834 - loss: 0.4498 - val_accuracy: 0.7792 - val_loss: 0.4551
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7818 - loss: 0.4490 - val_accuracy: 0.7857 - val_loss: 0.4539
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7801 - loss: 0.4480 - val_accuracy: 0.7857 - val_loss: 0.4541
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7818 - loss: 0.4471 - val_accuracy: 0.7857 - val_loss: 0.4549
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7834 - loss: 0.4470 - val_accuracy: 0.7857 - val_loss: 0.4567
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7769 - loss: 0.4457 - val_accuracy: 0.7792 - val_loss: 0.4557
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7801 - loss: 0.4451 - val_accuracy: 0.7922 - val_loss: 0.4559
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7801 - loss: 0.4441 - val_accuracy: 0.7792 - val_loss: 0.4558
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7785 - loss: 0.4436 - val_accuracy: 0.7922 - val_loss: 0.4559
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7818 - loss: 0.4429 - val_accuracy: 0.7857 - val_loss: 0.4539
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7736 - loss: 0.4422 - val_accuracy: 0.7792 - val_loss: 0.4554
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7801 - loss: 0.4418 - val_accuracy: 0.7857 - val_loss: 0.4532
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4409 - val_accuracy: 0.7857 - val_loss: 0.4534
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7834 - loss: 0.4405 - val_accuracy: 0.7857 - val_loss: 0.4538
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7834 - loss: 0.4398 - val_accuracy: 0.7857 - val_loss: 0.4554
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7850 - loss: 0.4394 - val_accuracy: 0.7857 - val_loss: 0.4544
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7850 - loss: 0.4386 - val_accuracy: 0.7857 - val_loss: 0.4553
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7834 - loss: 0.4380 - val_accuracy: 0.7857 - val_loss: 0.4554
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7818 - loss: 0.4381 - val_accuracy: 0.7857 - val_loss: 0.4543
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7818 - loss: 0.4369 - val_accuracy: 0.7922 - val_loss: 0.4551
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7834 - loss: 0.4365 - val_accuracy: 0.7857 - val_loss: 0.4541
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7818 - loss: 0.4361 - val_accuracy: 0.7857 - val_loss: 0.4542
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7818 - loss: 0.4354 - val_accuracy: 0.7857 - val_loss: 0.4553
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4350 - val_accuracy: 0.7857 - val_loss: 0.4548
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7785 - loss: 0.4355 - val_accuracy: 0.7922 - val_loss: 0.4549
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7834 - loss: 0.4345 - val_accuracy: 0.7922 - val_loss: 0.4541
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7785 - loss: 0.4344 - val_accuracy: 0.7922 - val_loss: 0.4534
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7785 - loss: 0.4338 - val_accuracy: 0.7922 - val_loss: 0.4536
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7801 - loss: 0.4331 - val_accuracy: 0.7922 - val_loss: 0.4539
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7785 - loss: 0.4326 - val_accuracy: 0.7922 - val_loss: 0.4555
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7785 - loss: 0.4320 - val_accuracy: 0.7922 - val_loss: 0.4552
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7785 - loss: 0.4316 - val_accuracy: 0.7922 - val_loss: 0.4547
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7801 - loss: 0.4312 - val_accuracy: 0.7922 - val_loss: 0.4540
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7769 - loss: 0.4308 - val_accuracy: 0.7857 - val_loss: 0.4542
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7801 - loss: 0.4305 - val_accuracy: 0.7857 - val_loss: 0.4533
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7818 - loss: 0.4302 - val_accuracy: 0.7922 - val_loss: 0.4556
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7850 - loss: 0.4301 - val_accuracy: 0.7922 - val_loss: 0.4552
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7850 - loss: 0.4295 - val_accuracy: 0.7987 - val_loss: 0.4522
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7866 - loss: 0.4292 - val_accuracy: 0.7987 - val_loss: 0.4534
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7850 - loss: 0.4291 - val_accuracy: 0.7987 - val_loss: 0.4525
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7850 - loss: 0.4284 - val_accuracy: 0.7987 - val_loss: 0.4518
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7866 - loss: 0.4284 - val_accuracy: 0.8117 - val_loss: 0.4516
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7866 - loss: 0.4276 - val_accuracy: 0.8052 - val_loss: 0.4518
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7818 - loss: 0.4265 - val_accuracy: 0.8052 - val_loss: 0.4519
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7818 - loss: 0.4267 - val_accuracy: 0.8052 - val_loss: 0.4522
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7834 - loss: 0.4261 - val_accuracy: 0.8052 - val_loss: 0.4520
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7850 - loss: 0.4255 - val_accuracy: 0.7987 - val_loss: 0.4522
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7850 - loss: 0.4255 - val_accuracy: 0.7987 - val_loss: 0.4525
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7883 - loss: 0.4253 - val_accuracy: 0.7987 - val_loss: 0.4510
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7883 - loss: 0.4245 - val_accuracy: 0.8052 - val_loss: 0.4506
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7883 - loss: 0.4241 - val_accuracy: 0.7987 - val_loss: 0.4513
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7899 - loss: 0.4238 - val_accuracy: 0.7987 - val_loss: 0.4512
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7899 - loss: 0.4236 - val_accuracy: 0.7987 - val_loss: 0.4522
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7866 - loss: 0.4234 - val_accuracy: 0.7987 - val_loss: 0.4519
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7883 - loss: 0.4227 - val_accuracy: 0.7987 - val_loss: 0.4511
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7899 - loss: 0.4224 - val_accuracy: 0.8052 - val_loss: 0.4514
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7899 - loss: 0.4223 - val_accuracy: 0.7987 - val_loss: 0.4508
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7899 - loss: 0.4218 - val_accuracy: 0.7922 - val_loss: 0.4515
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7932 - loss: 0.4215 - val_accuracy: 0.7987 - val_loss: 0.4501
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7948 - loss: 0.4207 - val_accuracy: 0.7987 - val_loss: 0.4502
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7948 - loss: 0.4210 - val_accuracy: 0.7987 - val_loss: 0.4497
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7915 - loss: 0.4208 - val_accuracy: 0.7922 - val_loss: 0.4504
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7932 - loss: 0.4204 - val_accuracy: 0.8052 - val_loss: 0.4493
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7932 - loss: 0.4199 - val_accuracy: 0.7987 - val_loss: 0.4491
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7915 - loss: 0.4193 - val_accuracy: 0.8117 - val_loss: 0.4484
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7915 - loss: 0.4189 - val_accuracy: 0.8117 - val_loss: 0.4488
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7964 - loss: 0.4192 - val_accuracy: 0.7922 - val_loss: 0.4486
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7948 - loss: 0.4191 - val_accuracy: 0.7987 - val_loss: 0.4475
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7915 - loss: 0.4187 - val_accuracy: 0.8052 - val_loss: 0.4474
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7964 - loss: 0.4181 - val_accuracy: 0.7922 - val_loss: 0.4488
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7948 - loss: 0.4181 - val_accuracy: 0.8052 - val_loss: 0.4479
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7915 - loss: 0.4170 - val_accuracy: 0.7987 - val_loss: 0.4493
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7948 - loss: 0.4169 - val_accuracy: 0.7922 - val_loss: 0.4487
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7964 - loss: 0.4166 - val_accuracy: 0.8052 - val_loss: 0.4486
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7948 - loss: 0.4164 - val_accuracy: 0.7987 - val_loss: 0.4502
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7964 - loss: 0.4165 - val_accuracy: 0.7987 - val_loss: 0.4483
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7948 - loss: 0.4160 - val_accuracy: 0.8052 - val_loss: 0.4477
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7964 - loss: 0.4156 - val_accuracy: 0.8052 - val_loss: 0.4475
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7997 - loss: 0.4159 - val_accuracy: 0.8052 - val_loss: 0.4492
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7932 - loss: 0.4151 - val_accuracy: 0.8052 - val_loss: 0.4476
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7932 - loss: 0.4149 - val_accuracy: 0.8052 - val_loss: 0.4479
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7964 - loss: 0.4148 - val_accuracy: 0.8052 - val_loss: 0.4476
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7964 - loss: 0.4144 - val_accuracy: 0.8052 - val_loss: 0.4477
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7964 - loss: 0.4145 - val_accuracy: 0.7987 - val_loss: 0.4495
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8013 - loss: 0.4145 - val_accuracy: 0.8052 - val_loss: 0.4493
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7980 - loss: 0.4138 - val_accuracy: 0.8052 - val_loss: 0.4480
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7980 - loss: 0.4136 - val_accuracy: 0.8117 - val_loss: 0.4485
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7964 - loss: 0.4135 - val_accuracy: 0.8052 - val_loss: 0.4496
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7964 - loss: 0.4130 - val_accuracy: 0.8117 - val_loss: 0.4488
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7997 - loss: 0.4132 - val_accuracy: 0.8052 - val_loss: 0.4495
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7980 - loss: 0.4128 - val_accuracy: 0.8117 - val_loss: 0.4464
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7948 - loss: 0.4125 - val_accuracy: 0.8117 - val_loss: 0.4470
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7980 - loss: 0.4118 - val_accuracy: 0.8117 - val_loss: 0.4479
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8029 - loss: 0.4124 - val_accuracy: 0.8117 - val_loss: 0.4488
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8029 - loss: 0.4119 - val_accuracy: 0.8052 - val_loss: 0.4480

#####1.How to select appropriate optimiser
#####2. No. of nodes in a layer
#####3. How to select no. of hidden layer
#####4. All in all one model

In [ ]:
pip install -U keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.83.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.16.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.1)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.7.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 1.3 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [ ]:
import kerastuner as kt

/tmp/ipykernel_696/1654478174.py:1: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  import kerastuner as kt

In [ ]:
def build_model(hp):

  model = Sequential()
  model.add(Dense(32,activation='relu',input_dim=8))
  model.add(Dense(1,activation='sigmoid'))

  optimizer=hp.Choice('optimizer',values = ['adam','sgd','rmsprop','adadelta'])
  model.compile(optimizer=optimizer,loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [ ]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=5)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

Trial 4 Complete [00h 00m 03s]
val_accuracy: 0.7857142686843872

Best val_accuracy So Far: 0.7857142686843872
Total elapsed time: 00h 00m 09s

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [ ]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(x_train,y_train,batch_size=32,epochs=100,initial_epoch=100,validation_data=(x_test,y_test))

In [ ]:
def build_model(hp):
  model = Sequential()
  units = hp.Int('units',min_value=8,max_value=128,step=8)
  model.add(Dense(units=units,activation='relu',input_dim=8))
  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [ ]:
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=5,
    directory= 'mydir'
)

Reloading Tuner from mydir/untitled_project/tuner0.json

In [ ]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'units': 40}

In [ ]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [ ]:
model.fit(x_train,y_train,batch_size=32,epochs=100,initial_epoch=100,validation_data=(x_test,y_test))

In [ ]:
def build_model(hp):
  model = Sequential()

  model.add(Dense(72,activation='relu',input_dim=8))

  for i in range(hp.Int('num_layers',min_value=1,max_value=10)):
    model.add(Dense(72,activation='relu'))
  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [ ]:
tuner = kt.RandomSearch(
    build_model,
    objective='val_accuracy',
    max_trials=3,
    directory= 'mydir',
    project_name='demo'
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

Trial 3 Complete [00h 00m 02s]
val_accuracy: 0.7922077775001526

Best val_accuracy So Far: 0.8376623392105103
Total elapsed time: 00h 00m 09s

In [ ]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 20 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [ ]:
model.fit(x_train,y_train,batch_size=32,epochs=100,initial_epoch=100,validation_data=(x_test,y_test))

In [ ]:
def build_model(hp):

  model = Sequential()

  counter = 0

  for i in range(hp.Int('num_layers',min_value=1,max_value=10)):
    if counter == 0:

      model.add(
          Dense(
            hp.Int('units' + str(i),min_value = 8,max_value = 128,step=8),
            activation=hp.Choice('activation' + str(i),values=['relu','tanh','sigmoid']),
            input_dim=8
          )
        )
      model.add(Dropout(hp.Choice('dropout' + str(i),values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))
    else:
      model.add(
          Dense(
            hp.Int('units' + str(i),min_value = 8,max_value = 128,step=8),
            activation=hp.Choice('activation' + str(i),values=['relu','tanh','sigmoid']),
            input_dim=8
          )
        )
      model.add(Dropout(hp.Choice('dropout' + str(i),values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))
    counter += 1

  model.add(Dense(1,activation='sigmoid'))

  model.compile(
      optimizer=hp.Choice('optimizer',values=['adam','sgd','rmsprop','adadelta']),
      loss='binary_crossentropy',
      metrics=['accuracy']
  )

  return model

In [ ]:
tuner = kt.RandomSearch(build_model,objective='val_accuracy',max_trials=3,directory='mydir',project_name='final')

Reloading Tuner from mydir/final/tuner0.json

In [ ]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 8,
 'units0': 56,
 'activation0': 'sigmoid',
 'optimizer': 'rmsprop',
 'units1': 112,
 'activation1': 'tanh',
 'units2': 120,
 'activation2': 'tanh',
 'units3': 24,
 'activation3': 'tanh',
 'units4': 112,
 'activation4': 'relu',
 'units5': 80,
 'activation5': 'tanh',
 'units6': 64,
 'activation6': 'tanh',
 'units7': 48,
 'activation7': 'tanh'}

In [ ]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 20 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [ ]:
model.fit(x_train,y_train,epochs=200,initial_epoch=6,validation_data=(x_test,y_test))

Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - accuracy: 0.7264 - loss: 0.5374 - val_accuracy: 0.7662 - val_loss: 0.5146
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7590 - loss: 0.5197 - val_accuracy: 0.7597 - val_loss: 0.4695
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7590 - loss: 0.5361 - val_accuracy: 0.7922 - val_loss: 0.5182
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7362 - loss: 0.5113 - val_accuracy: 0.7857 - val_loss: 0.5070
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7427 - loss: 0.4973 - val_accuracy: 0.7857 - val_loss: 0.4697
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7378 - loss: 0.5105 - val_accuracy: 0.7662 - val_loss: 0.5305
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7606 - loss: 0.5146 - val_accuracy: 0.7662 - val_loss: 0.5283
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7590 - loss: 0.5150 - val_accuracy: 0.7792 - val_loss: 0.4758
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7638 - loss: 0.5179 - val_accuracy: 0.7532 - val_loss: 0.5177
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7557 - loss: 0.5117 - val_accuracy: 0.7662 - val_loss: 0.5084
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7394 - loss: 0.5139 - val_accuracy: 0.7857 - val_loss: 0.5258
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7492 - loss: 0.5066 - val_accuracy: 0.7922 - val_loss: 0.5219
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.5036 - val_accuracy: 0.7792 - val_loss: 0.4775
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7541 - loss: 0.4926 - val_accuracy: 0.7922 - val_loss: 0.5297
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.5111 - val_accuracy: 0.7922 - val_loss: 0.4907
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7622 - loss: 0.5083 - val_accuracy: 0.7468 - val_loss: 0.5167
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4972 - val_accuracy: 0.7792 - val_loss: 0.4887
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7557 - loss: 0.4899 - val_accuracy: 0.7792 - val_loss: 0.5139
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7590 - loss: 0.5169 - val_accuracy: 0.7922 - val_loss: 0.4873
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7573 - loss: 0.5069 - val_accuracy: 0.8117 - val_loss: 0.5134
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7492 - loss: 0.4990 - val_accuracy: 0.7987 - val_loss: 0.5100
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7524 - loss: 0.5048 - val_accuracy: 0.7727 - val_loss: 0.4913
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4880 - val_accuracy: 0.7727 - val_loss: 0.4828
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7638 - loss: 0.5041 - val_accuracy: 0.7857 - val_loss: 0.4638
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4937 - val_accuracy: 0.7792 - val_loss: 0.4794
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4807 - val_accuracy: 0.6883 - val_loss: 0.5826
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7590 - loss: 0.4928 - val_accuracy: 0.7792 - val_loss: 0.5142
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7655 - loss: 0.4815 - val_accuracy: 0.7857 - val_loss: 0.4968
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7655 - loss: 0.4929 - val_accuracy: 0.7922 - val_loss: 0.4913
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7557 - loss: 0.4799 - val_accuracy: 0.7727 - val_loss: 0.4984
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7671 - loss: 0.4946 - val_accuracy: 0.7727 - val_loss: 0.4774
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7590 - loss: 0.4955 - val_accuracy: 0.7792 - val_loss: 0.4750
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7655 - loss: 0.4919 - val_accuracy: 0.7792 - val_loss: 0.4712
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7622 - loss: 0.4926 - val_accuracy: 0.7792 - val_loss: 0.4973
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7671 - loss: 0.4939 - val_accuracy: 0.7727 - val_loss: 0.5092
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7671 - loss: 0.4845 - val_accuracy: 0.7792 - val_loss: 0.4758
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7557 - loss: 0.4879 - val_accuracy: 0.7792 - val_loss: 0.4705
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7655 - loss: 0.4893 - val_accuracy: 0.7857 - val_loss: 0.4781
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7557 - loss: 0.4909 - val_accuracy: 0.7857 - val_loss: 0.4739
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7622 - loss: 0.4767 - val_accuracy: 0.7857 - val_loss: 0.4693
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7638 - loss: 0.4842 - val_accuracy: 0.7792 - val_loss: 0.4729
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7671 - loss: 0.5058 - val_accuracy: 0.7922 - val_loss: 0.4700
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4855 - val_accuracy: 0.7727 - val_loss: 0.4807
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4760 - val_accuracy: 0.7857 - val_loss: 0.4718
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4729 - val_accuracy: 0.7922 - val_loss: 0.4791
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7524 - loss: 0.4790 - val_accuracy: 0.7727 - val_loss: 0.4723
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7606 - loss: 0.4844 - val_accuracy: 0.7792 - val_loss: 0.4848
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7573 - loss: 0.4946 - val_accuracy: 0.7143 - val_loss: 0.5233
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4764 - val_accuracy: 0.7727 - val_loss: 0.4802
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4793 - val_accuracy: 0.7662 - val_loss: 0.5040
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4746 - val_accuracy: 0.7792 - val_loss: 0.4824
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7573 - loss: 0.4929 - val_accuracy: 0.7792 - val_loss: 0.4917
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4817 - val_accuracy: 0.7922 - val_loss: 0.4860
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7541 - loss: 0.4777 - val_accuracy: 0.7338 - val_loss: 0.4985
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7671 - loss: 0.4925 - val_accuracy: 0.7792 - val_loss: 0.4830
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7704 - loss: 0.4679 - val_accuracy: 0.7727 - val_loss: 0.4716
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7655 - loss: 0.4874 - val_accuracy: 0.7857 - val_loss: 0.4852
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7638 - loss: 0.4801 - val_accuracy: 0.8052 - val_loss: 0.4996
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7622 - loss: 0.4766 - val_accuracy: 0.7857 - val_loss: 0.4680
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7752 - loss: 0.4722 - val_accuracy: 0.7987 - val_loss: 0.4825
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7638 - loss: 0.4727 - val_accuracy: 0.7792 - val_loss: 0.4730
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4850 - val_accuracy: 0.7792 - val_loss: 0.4805
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7655 - loss: 0.4842 - val_accuracy: 0.7922 - val_loss: 0.4789
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4852 - val_accuracy: 0.7792 - val_loss: 0.4675
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.4784 - val_accuracy: 0.7792 - val_loss: 0.4788
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4810 - val_accuracy: 0.7857 - val_loss: 0.4818
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7638 - loss: 0.4865 - val_accuracy: 0.7727 - val_loss: 0.4848
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7590 - loss: 0.4699 - val_accuracy: 0.7922 - val_loss: 0.4872
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7655 - loss: 0.4643 - val_accuracy: 0.7857 - val_loss: 0.4840
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7622 - loss: 0.4916 - val_accuracy: 0.7792 - val_loss: 0.4858
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4637 - val_accuracy: 0.7857 - val_loss: 0.4779
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4763 - val_accuracy: 0.7727 - val_loss: 0.4695
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4809 - val_accuracy: 0.7987 - val_loss: 0.5016
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4693 - val_accuracy: 0.7727 - val_loss: 0.4842
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4809 - val_accuracy: 0.7792 - val_loss: 0.4954
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4821 - val_accuracy: 0.7922 - val_loss: 0.4783
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4826 - val_accuracy: 0.7792 - val_loss: 0.5247
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7590 - loss: 0.4838 - val_accuracy: 0.7857 - val_loss: 0.4839
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4777 - val_accuracy: 0.8052 - val_loss: 0.4847
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7573 - loss: 0.4838 - val_accuracy: 0.7597 - val_loss: 0.4966
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4673 - val_accuracy: 0.7727 - val_loss: 0.4752
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4692 - val_accuracy: 0.7792 - val_loss: 0.4830
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7606 - loss: 0.4711 - val_accuracy: 0.7792 - val_loss: 0.4856
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7590 - loss: 0.4752 - val_accuracy: 0.7857 - val_loss: 0.4942
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4611 - val_accuracy: 0.7922 - val_loss: 0.4829
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4733 - val_accuracy: 0.8117 - val_loss: 0.4852
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.4702 - val_accuracy: 0.8117 - val_loss: 0.4863
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4697 - val_accuracy: 0.7792 - val_loss: 0.4884
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7638 - loss: 0.4809 - val_accuracy: 0.7727 - val_loss: 0.4753
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4716 - val_accuracy: 0.7857 - val_loss: 0.4840
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4682 - val_accuracy: 0.7727 - val_loss: 0.4847
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4630 - val_accuracy: 0.7922 - val_loss: 0.4915
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7655 - loss: 0.4694 - val_accuracy: 0.7727 - val_loss: 0.4798
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4647 - val_accuracy: 0.8052 - val_loss: 0.4682
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7850 - loss: 0.4589 - val_accuracy: 0.7597 - val_loss: 0.5043
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4693 - val_accuracy: 0.7987 - val_loss: 0.4896
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4787 - val_accuracy: 0.7338 - val_loss: 0.4982
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4656 - val_accuracy: 0.7727 - val_loss: 0.4790
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4713 - val_accuracy: 0.7532 - val_loss: 0.5076
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7606 - loss: 0.4760 - val_accuracy: 0.7857 - val_loss: 0.4759
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4646 - val_accuracy: 0.7922 - val_loss: 0.4907
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7655 - loss: 0.4770 - val_accuracy: 0.7727 - val_loss: 0.4904
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4638 - val_accuracy: 0.7662 - val_loss: 0.5013
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4727 - val_accuracy: 0.7727 - val_loss: 0.4983
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4571 - val_accuracy: 0.7338 - val_loss: 0.5172
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4601 - val_accuracy: 0.7532 - val_loss: 0.5024
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4658 - val_accuracy: 0.7727 - val_loss: 0.4951
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4766 - val_accuracy: 0.7792 - val_loss: 0.4744
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4691 - val_accuracy: 0.8052 - val_loss: 0.4785
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7557 - loss: 0.4800 - val_accuracy: 0.7857 - val_loss: 0.4793
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4770 - val_accuracy: 0.7727 - val_loss: 0.4861
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4659 - val_accuracy: 0.8052 - val_loss: 0.4783
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4682 - val_accuracy: 0.7792 - val_loss: 0.4911
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7638 - loss: 0.4773 - val_accuracy: 0.7922 - val_loss: 0.4808
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4596 - val_accuracy: 0.7987 - val_loss: 0.4760
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4769 - val_accuracy: 0.7922 - val_loss: 0.4751
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4685 - val_accuracy: 0.7727 - val_loss: 0.5110
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4649 - val_accuracy: 0.7922 - val_loss: 0.4854
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4635 - val_accuracy: 0.7857 - val_loss: 0.4739
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4737 - val_accuracy: 0.7727 - val_loss: 0.4831
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4618 - val_accuracy: 0.7792 - val_loss: 0.4737
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7655 - loss: 0.4565 - val_accuracy: 0.7922 - val_loss: 0.4769
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.4580 - val_accuracy: 0.6948 - val_loss: 0.5276
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7671 - loss: 0.4792 - val_accuracy: 0.7597 - val_loss: 0.4871
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7622 - loss: 0.4581 - val_accuracy: 0.7857 - val_loss: 0.4841
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7638 - loss: 0.4653 - val_accuracy: 0.7532 - val_loss: 0.4777
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.4731 - val_accuracy: 0.7727 - val_loss: 0.4803
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4607 - val_accuracy: 0.7662 - val_loss: 0.4702
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4594 - val_accuracy: 0.7857 - val_loss: 0.4845
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7606 - loss: 0.4595 - val_accuracy: 0.7727 - val_loss: 0.4837
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4652 - val_accuracy: 0.7662 - val_loss: 0.4861
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.4701 - val_accuracy: 0.7468 - val_loss: 0.4753
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4740 - val_accuracy: 0.7727 - val_loss: 0.4856
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4583 - val_accuracy: 0.7792 - val_loss: 0.4902
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4477 - val_accuracy: 0.7792 - val_loss: 0.4777
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4586 - val_accuracy: 0.7922 - val_loss: 0.4760
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4540 - val_accuracy: 0.7792 - val_loss: 0.4888
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4670 - val_accuracy: 0.7857 - val_loss: 0.4926
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7573 - loss: 0.4676 - val_accuracy: 0.7792 - val_loss: 0.4705
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.4668 - val_accuracy: 0.7987 - val_loss: 0.4772
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4692 - val_accuracy: 0.7857 - val_loss: 0.4751
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4628 - val_accuracy: 0.7662 - val_loss: 0.4718
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7687 - loss: 0.4656 - val_accuracy: 0.7987 - val_loss: 0.4794
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7818 - loss: 0.4600 - val_accuracy: 0.7857 - val_loss: 0.4736
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7801 - loss: 0.4568 - val_accuracy: 0.7662 - val_loss: 0.4721
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7752 - loss: 0.4727 - val_accuracy: 0.7987 - val_loss: 0.4671
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7687 - loss: 0.4673 - val_accuracy: 0.7662 - val_loss: 0.4908
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7720 - loss: 0.4577 - val_accuracy: 0.7857 - val_loss: 0.4701
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7671 - loss: 0.4645 - val_accuracy: 0.7792 - val_loss: 0.4743
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4626 - val_accuracy: 0.7922 - val_loss: 0.4704
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7704 - loss: 0.4604 - val_accuracy: 0.7662 - val_loss: 0.4906
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4455 - val_accuracy: 0.7597 - val_loss: 0.4735
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4498 - val_accuracy: 0.7857 - val_loss: 0.4974
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7573 - loss: 0.4770 - val_accuracy: 0.7662 - val_loss: 0.4733
Epoch 161/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4469 - val_accuracy: 0.7662 - val_loss: 0.4887
Epoch 162/200